### PR TITLE
Add vscode extension

### PR DESCRIPTION
**Pull request by holgerschill**
Start by calling ./gradlew startCode
Server is self-contained in the extension

### CODE REVIEW

**Comment by holgerschill** [comment]
Start by calling ./gradlew startCode
Server is self-contained in the extension

**Comment by svenefftinge** [comment]
Thanks. Unfortunately it doesn't work on my machine.
the build fails eventually with
```
14:12:20.941 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
14:12:20.941 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'code'.
14:12:20.945 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
14:12:20.945 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'code'' finished with exit value -1 (state: FAILED)
14:12:20.945 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
14:12:20.945 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':vscode-calc-extension:installExtension'
14:12:20.945 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :vscode-calc-extension:installExtension FAILED
```

Any ideas?

**Comment by svenefftinge** [comment]
Does it assume `code` to be installed already?

**Comment by holgerschill** [comment]
Why did you close it?

**Comment by holgerschill** [comment]
Yes it assumes that code is installed.

**Comment by svenefftinge** [comment]
I merged it.

**Comment by holgerschill** [comment]
Ok. Did not see that you merged. Are you ok to have the server self-contained in the extension? We could create an extension that assumes the server started separately. For me it's easier to have it like this.

**Comment by svenefftinge** [comment]
Yes, I think it is good to have it contained. 
I am just a bit unsure about all the additional gradle logic.
It makes it convenient as long it works, but seems quite complex.

**Comment by svenefftinge** [comment]
I tried to keep it very simple with the other examples, as they are all consuming the uberjar. I would prefer to do it like that for the vscode extension, too

**Comment by holgerschill** [comment]
Ok. Then I will adjust the extension.

**Pull request merged**
